apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: todo
build:
  artifacts:
    - image: todo-backend
      context: . # プロジェクトのルートディレクトリを指定
      docker:
        dockerfile: docker/backend/Dockerfile
        buildArgs:
          JAR_FILE: "backend/target/*.jar"
    - image: todo-frontend
      context: frontend/todo-app
      docker:
        dockerfile: docker/frontend/Dockerfile
manifests:
  rawYaml:
    - k8s/postgres-deployment.yaml
    - k8s/postgres-pvc.yaml
    - k8s/postgres-service.yaml
    - k8s/secret.yaml
    - k8s/todo-backend-deployment.yaml
    - k8s/todo-backend-service.yaml
    - k8s/todo-frontend-deployment.yaml
    - k8s/todo-frontend-service.yaml
    - k8s/ingress.yaml
