apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: todo
build:
  artifacts:
    - image: todo-backend
      context: . # プロジェクトのルートディレクトリを指定
      docker:
        dockerfile: docker/backend/Dockerfile
        # Maven プロジェクトの場合、ビルドコンテキストのルートに pom.xml が存在しないため、buildArgs で指定が必要になる場合があります。
        buildArgs:
          JAR_FILE: "backend/target/*.jar"
manifests:
  rawYaml:
    - k8s/postgres-deployment.yaml
    - k8s/postgres-pvc.yaml
    - k8s/postgres-service.yaml
    - k8s/secret.yaml
    - k8s/todo-backend-deployment.yaml
    - k8s/todo-backend-service.yaml
